### ISSUE TITLE
File extension conversion

### ISSUE THREAD

**Issue by rpajo** [pqina/filepond-plugin-image-transform#2]
When uploading a .jpeg image the file extension is set to .jpg, yet the file metadata keeps the .jpeg extension.
I tracked it down to 
```ts
var renameFileToMatchMimeType = function renameFileToMatchMimeType(
   filename,
   format
) {
   var name = getFilenameWithoutExtension(filename);
   var extension = format === 'image/jpeg' ? 'jpg' : format.split('/')[1];
   return name + '.' + extension;
};
```
Is this a bug and should it be set to .jpeg or am i missing something?
```ts
var extension = format === 'image/jpeg' ? 'jpeg' : format.split('/')[1];
```

**Comment by rikschennink** [comment]
@rpajo Hi! What do you mean with file metadata? The mime type?

**Comment by rpajo** [comment]
Hey! My uploaded .jpeg image is saved as .jpg, but in the onFileUpload callback the file extension is still set as the original .jpeg so i get the wrong path due to this extension change.

**Comment by rikschennink** [comment]
Now I get it.

This is because a new file is created ( the original file is preserved ) and sent to the server. Suppose the output is forced to `image/png` then the filename should change as well.

I'm not sure how to fix this for now as I don't want to rename the original file ( renaming a jpeg to a png without changing the file format would create problems ).

Two quick temporary solutions:
- Use the [file-rename plugin](https://pqina.nl/filepond/docs/patterns/plugins/file-rename/) to rename the file in advance, but this could cause confusion ( as the interface will show a different name then the dropped file )
- As you're converting to `image/jpeg`, replace all extensions with `.jpg` in your `onFileUpload` callback.

**Comment by rpajo** [comment]
I have already implemented the file-rename plugin and it works fine now.
Thanks for the clarification.
